project: default
source:
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 27.23.0
  helm:
    values: |-
      server:
        persistentVolume:
          storageClassName: gp2
  chart: prometheus
destination:
  server: https://kubernetes.default.svc
  namespace: monitoring
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
