apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.23.0
    chart: prometheus
    helm:
      values: |-
        server:
          persistentVolume:
            enabled: true
            storageClass: gp2
        alertmanager:
          enabled: true
          persistence:
            enabled: false
            storageClass: gp2
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

