apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 3.1.0
    chart: opensearch
    helm:
      values: |-
        securityConfig:
          enabled: true
          #rolesMappingSecret: opensearch-security-config
          configSecret: opensearch-security-config2
        persistence:
          enabled: true
          storageClass: gp2
        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: Labas123!
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



