apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 3.1.0
    chart: opensearch
    helm:
      values: |-
        secretMounts:
          - name: opensearch-tls
            secretName: opensearch-node-tls
            path: /usr/share/opensearch/config/node-certs
            readOnly: true
          - name: opensearch-admin-tls
            secretName: opensearch-admin
            path: /usr/share/opensearch/config/admin-certs
            defaultMode: 0600
        config:
          opensearch.yml: |
            network.host: 0.0.0.0
            bootstrap.memory_lock: true
            plugins:
              security:
                #ssl:
                #  transport:
                #    enabled: true
                    #pemcert_filepath: node-certs/node1.pem
                    #pemkey_filepath: node-certs/node1-key.pem
                    #pemtrustedcas_filepath: node-certs/root-ca.pem
                #    enforce_hostname_verification: false       
                #  http:
                #    enabled: true
                    #pemcert_filepath: node-certs/node1.pem
                    #pemkey_filepath: node-certs/node1-key.pem
                    #pemtrustedcas_filepath: node-certs/root-ca.pem
                allow_unsafe_democertificates: true
                allow_default_init_securityindex: true
                #nodes_dn:
                #  - O=Lino,ST=Vilnius,C=LT
                #authcz.admin_dn:
                #  - O=Lino,ST=Vilnius,C=LT
                audit:
                  type: internal_opensearch
                enable_snapshot_restore_privilege: true
                check_snapshot_restore_write_privileges: true
                restapi:
                  roles_enabled: ["all_access", "security_rest_api_access"]
        persistence:
          enabled: true
          storageClass: gp2
        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: Labas123!
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



