apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-ca-node-tls
  secretName: root-ca-node-tls
  privateKey:
    algorithm: ECDSA
    size: 521
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-issuer
spec:
  ca:
    secretName: root-ca-node-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-tls
  namespace: monitoring
spec:
  secretName: opensearch-tls
  commonName: opensearch-tls
  dnsNames:
    - opensearch-cluster-master-0
    - opensearch-cluster-master-1
    - opensearch-cluster-master-2
  subject:
    organizations:
      - DevOpsLT
    organizationalUnits:
      - OpsTeam
    countries:
      - LT
    localities:
      - Vilnius    
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 521
    encoding: PKCS8
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-tls
  namespace: monitoring
spec:
  secretName: opensearch-admin-tls
  commonName: opensearch-admin-tls
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 521
    encoding: PKCS8
  subject:
    organizations:
      - DevOpsLT
    organizationalUnits:
      - OpsTeam
    countries:
      - LT
    localities:
      - Vilnius    
