apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 3.1.0
    chart: opensearch
    helm:
      values: |-
        secretMounts:
          - name: opensearch-tls
            secretName: opensearch-node-tls
            path: /usr/share/opensearch/config/node-certs
            readOnly: true
          - name: opensearch-admin-tls
            secretName: opensearch-admin-tls
            path: /usr/share/opensearch/config/admin-certs
            defaultMode: 0600
        config:
          opensearch.yml: |
            network.host: 0.0.0.0
            bootstrap.memory_lock: true
            plugins:
              security:
                ssl:
                  transport:
                    enabled: true
                    pemcert_filepath: node-certs/tls.crt
                    pemkey_filepath: node-certs/tls.key
                    pemtrustedcas_filepath: node-certs/ca.crt
                    enforce_hostname_verification: false       
                  http:
                    enabled: true
                    pemcert_filepath: node-certs/tls.crt
                    pemkey_filepath: node-certs/tls.key
                    pemtrustedcas_filepath: node-certs/ca.crt
                allow_unsafe_democertificates: false
                allow_default_init_securityindex: true
                nodes_dn:
                  - CN=*,O=LT-Linas
                authcz.admin_dn:
                  - CN=admin.linas.local,O=LT-Linas
                audit:
                  type: internal_opensearch
                enable_snapshot_restore_privilege: true
                check_snapshot_restore_write_privileges: true
                restapi:
                  roles_enabled: ["all_access", "security_rest_api_access"]
        securityConfig:
          enabled: true        
          securityadmin:
            enable: true
          config:
            dynamic:
              authc:
                openid_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: 1
                  http_authenticator:
                    type: openid
                    challenge: true
                    config:
                      subject_key: email
                      roles_key: cognito:groups
                      openid_connect_url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_wuTtDOQcv/.well-known/openid-configuration
                    authentication_backend:
                      type: noop  
          path: "/usr/share/opensearch/config/opensearch-security"
          #rolesMappingSecret: opensearch-security-config
        persistence:
          enabled: true
          storageClass: gp2
        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: Labas123!
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



