apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 3.1.0
    chart: opensearch
    helm:
      values: |-
        secretMounts:
          - name: opensearch-tls
            secretName: opensearch-tls
            path: /usr/share/opensearch/config/certs      
        config:
          opensearch.yml: |
            cluster.name: "opensearch-cluster"
            node.name: "opensearch-node-0"
            network.host: 0.0.0.0
            
            bootstrap.memory_lock: true
            plugins.security.ssl.transport.enabled: true
            plugins.security.ssl.transport.pemcert_filepath: certs/tls.crt
            plugins.security.ssl.transport.pemkey_filepath: certs/tls.key
            plugins.security.ssl.transport.pemtrustedcas_filepath: certs/ca.crt
            plugins.security.ssl.transport.enforce_hostname_verification: false
            
            plugins.security.ssl.http.enabled: true
            plugins.security.ssl.http.pemcert_filepath: certs/tls.crt
            plugins.security.ssl.http.pemkey_filepath: certs/tls.key
            plugins.security.ssl.http.pemtrustedcas_filepath: certs/ca.crt
            
            plugins.security.allow_unsafe_democertificates: false
            plugins.security.allow_default_init_securityindex: true
            plugins.security.nodes_dn:
              - "O=LT-Linas, CN=opensearch.local"
            plugins.security.authcz.admin_dn:
              - "O=LT-Linas, CN=opensearch.local"
            
            plugins.security.audit.type: internal_opensearch
            plugins.security.enable_snapshot_restore_privilege: true
            plugins.security.check_snapshot_restore_write_privileges: true
            plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
            

      
        securityConfig:
          enabled: true        
          securityadmin:
            enable: true
          config:
            dynamic:
              nodes_dn:
                - "O=LT-Linas, CN=*"
              authc:
                openid_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: 1
                  http_authenticator:
                    type: openid
                    challenge: true
                    config:
                      subject_key: email
                      roles_key: cognito:groups
                      openid_connect_url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XcL5BjfTU/.well-known/openid-configuration
                    authentication_backend:
                      type: noop  
          path: "/usr/share/opensearch/config/opensearch-security"
          rolesMappingSecret: opensearch-security-config
        persistence:
          enabled: true
          storageClass: gp2
        extraEnvs:
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            value: Labas123!
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



