apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postee
  namespace: argo-cd
spec:
  destination:
    namespace: postee
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: v2.14.0
    chart: postee
    helm:
      parameters:
        - name: persistentVolume.enabled
          value: 'true'
      values: |-
        persistentVolume:
          storageClass: gp2
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
