apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
spec:
  destination:
    namespace: trivy-system
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.29.3
    chart: trivy-operator
    helm:
      values: ''
      parameters:
        - name: trivy.ignoreUnfixed
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
