apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: aws-ebs-csi-driver
spec:
  forProvider:
    region: us-east-1
    addonName: aws-ebs-csi-driver
    clusterName: test
    resolveConflicts: OVERWRITE
    podIdentityAssociation:
      - roleArn: arn:aws:iam::975050322104:role/AmazonEKSPodIdentityAmazonEBSCSIDriverRole
        serviceAccount: ebs-csi-controller-sa
  providerConfigRef:
    name: default
  deletionPolicy: Delete